---
- src: geerlingguy.jenkins
- src: srsp.oracle-java
- src: https://github.com/GSA/ansible-os-rhel-7
  name: gsa_hardening
- src: https://github.com/GSA/ansible-https-proxy
  name: gsa.https-proxy
- src: https://github.com/GSA/jenkins-deploy
  name: gsa.jenkins
- src: mauromedda.ansible_role_terraform
- src: mauromedda.ansible_role_terragrunt